[build]
  publish = "."

[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "no-cache"
